apiVersion: "logging.openshift.io/v1"
kind: ClusterLogForwarder
metadata:
  name: instance 
  namespace: openshift-logging 
spec:
  outputs:
   - name: external-elk 
     type: "elasticsearch"
     url: tcp://192.168.130.1:5000
  pipelines:
   - name: all-to-external
     inputRefs:
      - infrastructure
      - application
      - audit
     outputRefs:
      - external-elk
   - name: all-to-default
     inputRefs:
      - infrastructure
      - application
      - audit
     outputRefs:
      - default
